/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\model\robot.glb 
Author: Ragian (https://sketchfab.com/Ragian)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/robots-ringworkers-e71e5107e0894dc997c9df971f99c281
Title: Robots Ringworkers
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Robot = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('Model/robot.glb')
  console.log(nodes,'노드노드22', materials, '메테리얼22')
  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[61.803, 0, -188.766]}>
        <mesh geometry={nodes.group1_pasted__polySurface2_M_Mecha1_Blinn2_0.geometry} material={materials.M_Mecha1_Blinn2} />
        <mesh geometry={nodes.group1_pasted__polySurface2_M_Mecha1_Blinn1_1_0.geometry} material={materials.M_Mecha1_Blinn1_1} />
        <mesh geometry={nodes.group1_pasted__polySurface2_M_Mecha1_Blinn1_0.geometry} material={materials.M_Mecha1_Blinn1} />
        <mesh geometry={nodes.group1_pasted__polySurface2_M_Mecha1_Blinn1_0_1.geometry} material={materials.M_Mecha1_Blinn1} />
        <mesh geometry={nodes.group1_pasted__polySurface2_blinn2_0.geometry} material={materials.blinn2} />
      </group>
    </group>
  )
})

useGLTF.preload('Model/robot.glb')
